[package]
org = "ballerinax"
name = "mysql"
version = "1.18.0"
authors = ["Ballerina"]
keywords = ["Client", "Network", "SQL", "RDBMS", "MySQL", "Vendor/Oracle", "Area/Database", "Type/Connector", "Type/Trigger"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mysql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mysql-native"
version = "1.18.0"
path = "../native/build/libs/mysql-native-1.18.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.19.0"
path = "./lib/sql-native-1.19.0-20260331-111100-8a9f7f8.jar"
