CREATE DATABASE IF NOT EXISTS JSON_TYPE_DB;

USE JSON_TYPE_DB;

DROP TABLE IF EXISTS JsonTable;

CREATE TABLE IF NOT EXISTS JsonTable (
  id INT NOT NULL,
  json_value JSON NULL,
  PRIMARY KEY (id)
);

INSERT INTO JsonTable (id, json_value) VALUES (1, '{\"key\":\"value\"}');