CREATE DATABASE IF NOT EXISTS XA_TRANSACTION_2;

USE XA_TRANSACTION_2;

CREATE TABLE IF NOT EXISTS Salary (
  ID INTEGER,
  VALUE DOUBLE
);

CREATE TABLE IF NOT EXISTS SalaryTrx (
  ID INTEGER,
  VALUE DOUBLE,
  PRIMARY KEY (ID)
);

INSERT INTO SalaryTrx VALUES (20, 30000);

