name: fraud-detection-example

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cdc
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance_db
      MYSQL_USER: cdc_user
      MYSQL_PASSWORD: cdc_password
    volumes:
      - ./db-scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
