CREATE DATABASE IF NOT EXISTS LOCAL_TRANSACTION;

USE LOCAL_TRANSACTION;

CREATE TABLE IF NOT EXISTS Customers(
  customerId INTEGER NOT NULL AUTO_INCREMENT,
  firstName  VARCHAR(300),
  lastName  VARCHAR(300),
  registrationID INTEGER,
  creditLimit DOUBLE,
  country  VARCHAR(300),
  PRIMARY KEY (customerId)
);
