DROP DATABASE IF EXISTS testDB;
CREATE DATABASE testDB;
USE testDB;

DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES (
  EMPLOYEENUMBER int(11) NOT NULL,
  LASTNAME varchar(50) NOT NULL,
  FIRSTNAME varchar(50) NOT NULL,
  EXTENSION varchar(10) NOT NULL,
  EMAIL varchar(100) NOT NULL,
  OFFICECODE varchar(10) NOT NULL,
  REPORTSTO int(11) DEFAULT NULL,
  JOBTITLE varchar(50) NOT NULL,
  PRIMARY KEY (EMPLOYEENUMBER),
  KEY REPORTSTO (REPORTSTO),
  KEY OFFICECODE (OFFICECODE),
  CONSTRAINT FK_EmployeesManager FOREIGN KEY (REPORTSTO) REFERENCES EMPLOYEES(EMPLOYEENUMBER),
  CONSTRAINT FK_EmployeesOffice FOREIGN KEY (OFFICECODE) REFERENCES OFFICES(OFFICECODE)
);

DROP TABLE IF EXISTS OFFICES;
CREATE TABLE OFFICES (
  OFFICECODE varchar(10) NOT NULL,
  PRIMARY KEY (OFFICECODE)
);

DELIMITER $$
DROP PROCEDURE IF EXISTS getEmpsName $$
CREATE PROCEDURE getEmpsName(IN EMPNUMBER INT, OUT FNAME VARCHAR(20))
BEGIN
   SELECT FIRSTNAME INTO FNAME
   FROM EMPLOYEES
   WHERE EMPLOYEENUMBER = EMPNUMBER;
END $$
DELIMITER ;
